cc_library(
    name = "cxxavl",
    srcs = ["avl.cxx"],
    hdrs = ["avl.hxx"],
    copts = ["-std=c++17"],
    includes = ["."],
    visibility = ["//visibility:public"],
    deps = ["@boost//:intrusive"],
)
