cc_library(
    name = "zset",
    srcs = ["zset.cxx"],
    hdrs = ["zset.hxx"],
    copts = ["-std=c++23"],
    visibility = ["//visibility:public"],
    deps = [
        "//avl/c:cavl",
        "//map/c:cmap",
    ],
)
