cc_test(
    name = "test_c_avl",
    srcs = ["test_c_avl.cxx"],
    deps = [
        "//avl/c:cavl",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "test_cxx_avl",
    srcs = ["test_cxx_avl.cxx"],
    deps = [
        "//avl/cxx:cxxavl",
        "@gtest//:gtest_main",
    ],
)
