cc_test(
    name = "test_lookup",
    srcs = ["test_lookup.cxx"],
    deps = [
        "//map/c:cmap",
        "//map/cxx:cxxmap",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "test_pop",
    srcs = ["test_pop.cxx"],
    deps = [
        "//map/c:cmap",
        "//map/cxx:cxxmap",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "test_destroy",
    srcs = ["test_destroy.cxx"],
    deps = [
        "//map/c:cmap",
        "//map/cxx:cxxmap",
        "@gtest//:gtest_main",
    ],
)
