name: C++23 | GCC 14 | Bazel | Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    container:
      image: gcc:14

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bazelisk
        uses: philwo/setup-bazelisk@v1

      - name: Build project with GCC 14
        run: bazel build --cxxopt='-std=c++23' //...

      - name: Run tests with GCC 14
        run: bazel test --cxxopt='-std=c++23' //...
