name: trei linii de coxx

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    container:
      image: gcc:14

    steps:
      - name: Install Clang-Tidy & Clang-Format
        run: apt-get update && apt-get install -y clang-tidy clang-format sudo

      - name: Install Python
        run: apt-get update && apt-get install -y python-is-python3 python3-pip python3-venv sudo

      - name: Create non-root user
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bazelisk
        uses: philwo/setup-bazelisk@v1

      - name: Set Git safe directory
        run: git config --global --add safe.directory /__w/coxx/coxx

      - name: Format code with Clang-Format
        run: |
          find . -name "*.cxx" -o -name "*.hxx" -o -name "*.c" -o -name "*.h" | xargs clang-format -i
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          if ! git diff --quiet && ! git diff --staged --quiet; then
            git commit -m "Apply clang-format changes"
            git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref }}
          fi

      - name: Switch to non-root user
        run: |
          chown -R builder:builder .
          su builder

      - name: Create virtual environment & install dependencies
        run: |
          su builder -c 'python -m venv venv'
          su builder -c '. venv/bin/activate && pip install tqdm colorama'

      - name: Build project with GCC 14
        run: su builder -c 'bazel build --cxxopt='-std=c++23' //...'

      - name: Generate compile_commands.json
        run: su builder -c 'bazel run @hedron_compile_commands//:refresh_all -- --cxxopt="-std=c++23"'

      - name: Run Clang-Tidy over the project & supress failure
        run: su builder -c 'clang-tidy -p=. $(find . -name "*.cxx" -o -name "*.hxx") || true'

      - name: Run unit tests with GCC 14
        run: su builder -c 'bazel test --cxxopt="-std=c++23" //...'

      - name: Run integration test with Python
        run: su builder -c '. venv/bin/activate && python test_commands.py'
